### ISSUE TITLE
Update-Changelog adding #[unreleased] under # tag on Linux

### ISSUE THREAD

**Issue by gaelcolas** [natescherer/ChangelogManagement#11]
Hi,
Thanks for this nifty module!

I think I've came accross with an issue when running `Update-ChangeLog` on Linux (or WSL). Here's the output I get when running on Linux: https://github.com/gaelcolas/Sampler/pull/38/commits/208996791b0a939336b01357cd73123961465c5b
See the second, undesired `## [Unreleased]`

```
## [Unreleased]

## [v0.92.2] - 2019-10-15
## [Unreleased]

### Fixed

- Add condition to trigger deployment stage when building a tag (not master)

## [v0.92.0] - 2019-10-15

[...]
```

This is not happening when running on WPS **5.1** or **PS 6.2.1** and **PS 7-preview4** on Windows:
```
## [Unreleased]

## [v0.92.1] - 2019-10-15

### Fixed

- Add condition to trigger deployment stage when building a tag (not master)

## [v0.92.0] - 2019-10-15
[...]
```

This error occured on an Azure DevOps build agent:
```
pool:
  vmImage: 'ubuntu 16.04'
```
I could reproduce this error on WSL.

```
uname -a
Linux DESKTOP-0A9DA6S 4.4.0-18362-Microsoft #10000-Microsoft Fri Jun 21 11:23:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gaelcolas** [comment]
The issue is with your line:
```
$NL = [System.Environment]::NewLine
```
When the New Line has been created on Windows, but the parsing is done on Linux, that's not working anymore...
If I replace by the following when running on Linux it works...
```
$NL = "`r`n"
```
I guess using a more flexible regex during parsing could help... something like "\r?\n".

**Comment by natescherer** [comment]
Apologies for the delay on looking at this; Been busy work work and travel (I’m at MS Ignite right now, in fact). I will take a look at this no later than this weekend.

**Comment by johlju** [comment]
Would be great to have this issue resolved. @natescherer are you working on a fix to resolve this?

**Comment by johlju** [comment]
This row is the problem 

https://github.com/natescherer/ChangelogManagement/blob/627f45bea0c684024439ee86b9ffd1afd8df7311/src/ChangelogManagement.psm1#L337

Changing the row to the suggestion by @gaelcolas will solve the issue.

```powershell
$NewRelease = $ChangelogData.Unreleased.RawData -replace "## \[Unreleased\]\r?\n",""
```

**Comment by PlagueHO** [comment]
Keen to get this one through.

**Comment by johlju** [comment]
Sent in PR https://github.com/natescherer/ChangelogManagement/pull/12.

**Comment by natescherer** [comment]
I'm extremely sorry for the delay on this! PR has been merged and version 2.1.4 is now live in the Gallery. @gaelcolas  and @johlju, I've also given you attribution in the authors section of the README.

I'm glad all of you are finding my module useful and I do apologize for leaving you hanging. Things have changed in my life where I now have more time to devote to personal projects and I'll do my darnedest to not let this lapse again. Please let me know if you have any issues!

**Comment by johlju** [comment]
@natescherer thanks a lot! No worries, we all have a life outside of OSS too. 😃 We continue help fix issues when we find them. Thanks again! 🙇

**Comment by natescherer** [comment]
@all-contributors please add @gaelcolas for code
