### ISSUE TITLE
Error when running update changelog

### ISSUE THREAD

**Issue by rcdailey** [natescherer/ChangelogManagement#13]
I'm running this command:

```
$LinkPattern = @{
    FirstRelease = "https://github.com/rcdailey/trash-updater/releases/tag/v{CUR}"
    NormalRelease = "https://github.com/rcdailey/trash-updater/compare/v{PREV}...v{CUR}"
    Unreleased = "https://github.com/rcdailey/trash-updater/compare/v{CUR}...HEAD"
}

Update-Changelog -ReleaseVersion $version -LinkMode Automatic -LinkPattern $LinkPattern
```

I get this error:

```
InvalidOperation: C:\Users\robert\Documents\PowerShell\Modules\ChangelogManagement\2.1.4\ChangelogManagement.psm1:107:22
Line |
 107 |  …         "Date" = Get-Date ($Release -split "\] \- ")[1].Split($NL)[0]
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```

I'm running Powershell 7.1.3

**Comment by natescherer** [comment]
Would you mind posting/linking to the changelog you're running the command on? The error leads me to believe the cmdlet is having trouble parsing it.

**Comment by rcdailey** [comment]
Sure, here you go: https://github.com/rcdailey/trash-updater/blob/2eefdc03258ba491478de2057e5e89255d2d024c/CHANGELOG.md

I sent you to the revision of the file prior to my latest release which showed the error.

**Comment by rcdailey** [comment]
I set `$version` to 1.2.0 in the command I ran in my OP.

**Comment by rcdailey** [comment]
@natescherer Did my last replies get you all the information you requested? Let me know if there's more I need to do for you to be able to test. Thank you.

**Comment by natescherer** [comment]
Apologies that I forgot about this for so long. Took a look and this is because some parts of your file are out of the specification:

```
## [1.0.0] - 2021-04-14

See the [Python Migration Guide][py-mig] for details on how to update your YAML configuration.

[py-mig]: https://github.com/rcdailey/trash-updater/wiki/Python-Migration-Guide
````

That part specifically. Unfortunately I don't think there's really any way to have the module work with files that aren't 100% compliant with the specification due to the nature of the string parsing. Sorry!

**Comment by rcdailey** [comment]
How is this "out of the specification"? No where in the Keep A Changelog documentation does it say I can't use markdown links. It even explicitly states that there's not really a standard, it's just a guideline for how to write better changelogs.

**Comment by natescherer** [comment]
I have no interested in having an argument about what is and is not a specification. Feel free to fork this module and release your own version that meets your needs, the MIT License allows for that. Thanks!
