### ISSUE TITLE
Newline is removed at the end of the file

### ISSUE THREAD

**Issue by rcdailey** [natescherer/ChangelogManagement#14]
# Summary

I am running the `Update-Changelog` as follows:

```pwsh
Update-Changelog -ReleaseVersion $version -LinkMode Automatic -LinkPattern @{
    FirstRelease = "https://github.com/rcdailey/trash-updater/releases/tag/v{CUR}"
    NormalRelease = "https://github.com/rcdailey/trash-updater/compare/v{PREV}...v{CUR}"
    Unreleased = "https://github.com/rcdailey/trash-updater/compare/v{CUR}...HEAD"
}
```

Once the update is finished, the newline I had at the end of my `CHANGELOG.md` is removed.

# Steps to Reproduce

1. Create a `CHANGELOG.md` with at least 1 version in it and some content under `[Unreleased]`.
1. Ensure that there is a single blank line at the end of the file.
1. Do a `git add` to snapshot the changes prior to updating changelog
1. Run the command issued in the Summary section above
1. Do a `git diff` and notice that the newline at the end of the file was removed.

# Expected Behavior

If a newline is present at the end of the file, that newline should be retained. If no newline was originally at the end, do not add one. The goal, as I see it, is to minimize unnecessary changes in the file.

The workaround I'm using right now is to execute the following commands after I do `Update-Changelog`:

```pwsh
$content = Get-Content -Path .\CHANGELOG.md
Set-Content -Path .\CHANGELOG.md -Value $content
```

**Comment by natescherer** [comment]
Hello! Apologies for letting this sit for so long. This is a reasonable request but also runs counter to the specification. If you look at https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md?plain=1 you'll see there is no newline at the end of the file (even though this is arguably against markdown best practices). I will leave this open and think about implementing a flag like -PreserveWhitespace or something equivalent, but I wouldn't consider this a bug per se.

**Comment by rcdailey** [comment]
That is not a "specification". That's an example of how someone has written their changelog. If you are coding against that, then you are arbitrarily limiting your software. See the official [FAQ](https://keepachangelog.com/en/1.0.0/#frequently-asked-questions):

![image](https://user-images.githubusercontent.com/1768054/197011563-f1681b60-8628-4ec5-825f-c8a1ebbe027b.png)

I have yet to find anything that explicitly states otherwise.

The bug here is that your tool is modifying parts of my document that did not need to change in order to accomplish its task. This isn't about adding new lines or not. It's about not making unnecessary changes.

Adding a flag isn't the right solution here, in my view. I think it's simpler than that: Just don't touch the text at the end of the file.

**Comment by natescherer** [comment]
I have no interested in having an argument about what is and is not a specification. Feel free to fork this module and release your own version that meets your needs, the MIT License allows for that. Thanks!
