### ISSUE TITLE
Get-ChangelogData Empty Unreleased Section output Not $null

### ISSUE THREAD

**Issue by natescherer** [natescherer/ChangelogManagement#25]
When there is an empty Unreleased section, the output is an empty PSCustomObject, which PowerShell does not treat the same as $null. Should fix at some point.

**Comment by johlju** [comment]
Hitting this. Our deploy Pester tests started to fail since RawData is no longer set correctly.

**Comment by johlju** [comment]
By always returning the PSCustomObject even with empty values for 'Added', Changed', and so on, it is possible to validate that release has the expected information. By always passing the PSCUstomObject we also get the RawData which we can validate that the changelog indeed contain a Unreleased section.

**Comment by natescherer** [comment]
@johlju Now live in the Gallery at v3.0.1!

**Comment by johlju** [comment]
Thank you!
