### ISSUE TITLE
Are intro lines required

### ISSUE THREAD

**Issue by jdhitsolutions** [natescherer/ChangelogManagement#32]
When I setup a new change log, I get this boilerplate.

```markdown
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
```

If I make any changes to this, will I break any commands? For example, I'd like the title to be `# MyModule Changelog`. I also might want to have my own intro text and/or delete what `New-ChangeLog` creates. Will this lead to problems later?

**Comment by natescherer** [comment]
This isn't something I've tested, to be honest, but a quick look at the code makes me think that, as long as you:
1) Have some kind of header
2) That header doesn't contain `## [`

it should be fine.
