### ISSUE TITLE
Including Datetime

### ISSUE THREAD

**Issue by jdhitsolutions** [natescherer/ChangelogManagement#33]
For projects with faster release cadences, wouldn't it make sense to include a timestamp? Would something like this be valid?

```markdown
## [1.3.22] - 2022-12-28 16:45:11
```

**Comment by natescherer** [comment]
Afraid this is a request for https://github.com/olivierlacan/keep-a-changelog repo rather than this repo. If a newer version of the Keep a Changelog standard adds time to the datestamp, I'll gladly support it, but I'm not adding anything that doesn't exist upstream.
