### ISSUE TITLE
Support markdown formatting in data

### ISSUE THREAD

**Issue by jdhitsolutions** [natescherer/ChangelogManagement#34]
I added an entry to the changelog using markdown formatting.

```powershell
add-ChangelogData -Type Added -Data "added aliases of `due` and `deadline` for `DueDate` for the `psworkitem` type."
```

Unfortunately, the formatting is dropped.  This is what I see:

```markdown
## [Unreleased]
### Added
- added aliases of due and deadline for DueDate for the psworkitem type.
```

It would be helpful to keep the formatting.

**Comment by natescherer** [comment]
Actually, this isn't a case of formatting being dropped as much as PowerShell just being PowerShell. The backtick is the PowerShell escape character, so if you need to includes a literal backtick in any PowerShell strings, you need to put in two backticks.

i.e.

```
add-ChangelogData -Type Added -Data "added aliases of ``due`` and ``deadline`` for ``DueDate`` for the ``psworkitem`` type."
```
