### ISSUE TITLE
Is it possible to use the .Net standard [System.Version] type four (4) valued version identifier?

### ISSUE THREAD

**Issue by Liturgist** [natescherer/ChangelogManagement#37]
When I use a four (4) valued version identifier, the following message appears. But the CHANGELOG.md appears to be updated correctly.

[PS C:\src\localrepo\> Update-Changelog -ReleaseVersion 1.0.1.7 -LinkMode None
InvalidOperation: C:\...\Documents\PowerShell\Modules\ChangelogManagement\3.0.1\public\Get-ChangelogData.ps1:116
Line |
116  |  … "Date"    = Get-Date ($Release -split "\] \- ")[1].Split($FileNewline …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.](url)

Should the parameter
[    [string]$ReleaseVersion
](url)be
[    [version]$ReleaseVersion](url)

**Comment by natescherer** [comment]
Hi @Liturgist, Can you share the full CHANGELOG.md file you're trying to run this on, please?

**Comment by Liturgist** [comment]
My apologies. I cannot find the `CHANGELOG.md` that produced the problem. I did not leave myself enough bread crumbs to backtrack to it. Closing.
