### ISSUE TITLE
Get-ChangelogData reads incorrectly when there is no UNRELEASED section

### ISSUE THREAD

**Issue by jcharlesworthuk** [natescherer/ChangelogManagement#9]
Steps to reproduce...

Use a changelog like this with no [Unreleased] section

```
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [1.0.0] - 2017-06-20
### Added
- New visual identity by [@tylerfortune8](https://github.com/tylerfortune8).
- Version navigation.
- Links to latest released version in previous versions.
```

Run

` Get-ChangelogData | Select -Property Unreleased`

Expected: To return null or some empty object
Actual: Returns the latest release.

In the above example this will not return our one release
` Get-ChangelogData | Select -Property Released`

I think we should change **Get-ChangelogData** to match the actual text [Unreleased] as per the spec, instead of simply returning the first "block".

**Comment by jcharlesworthuk** [comment]
This is the line that should be checking for the tag [Unreleased]
[ChangelogManagement.psm1#L62](https://github.com/natescherer/ChangelogManagement/blob/master/src/ChangelogManagement.psm1#L62)

**Comment by natescherer** [comment]
Good catch! I'll take a look at this this weekend and issue a 2.1.3 release (if you'd like to take a crack at it yourself before then, you're also welcome to open a PR, just let me know).

**Comment by jcharlesworthuk** [comment]
Sure, I have created a pull request #10

**Comment by natescherer** [comment]
PR looks good, I merged it. I'll add a Pester test with a missing Unreleased section and make a new release; should be later today or tomorrow.

Thanks for contributing!

**Comment by natescherer** [comment]
2.1.3 is now up in the PowerShell gallery, and you're added to the Authors list in the README. Thanks again!
